- job:
    name: ospurge-functional
    parent: legacy-dsvm-base
    run: playbooks/ospurge-functional/run.yaml
    post-run: playbooks/ospurge-functional/post.yaml
    timeout: 3600
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/ospurge
      - openstack/designate
      - openstack/python-designateclient
    irrelevant-files: &dsvm-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^\.testr.conf$
      - ^LICENSE$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tox.ini$

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-cover-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - ospurge-functional
    gate:
      jobs:
        - ospurge-functional
